name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Gradle
        run: ./gradlew test

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Lint with Checkstyle
        run: ./gradlew checkstyleMain

      - name: Lint Dockerfile with Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    needs: [test, lint]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Runnable Jar with Gradle
        run: ./gradlew bootJar

  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
